eureka:
  registry:
    instance[0] :
      hostname : peer1
      port : 1111
  client:
    service-url:
      defaultZone: http://${eureka.registry.instance[0].hostname}:${eureka.registry.instance[0].port}/eureka/
server:
  port: 1115
spring:
  application:
    name: feign-consumer