eureka:
  registry:
    hostname1: localhost
    port1: 1111
    hostname2: localhost
    port2: 1112
  client:
    service-url:
      defaultZone: http://${eureka.registry.hostname1}:${eureka.registry.port1}/eureka/,http://${eureka.registry.hostname2}:${eureka.registry.port2}/eureka/
server:
  port: 1113
spring:
  application:
    name: hello-services