server:
  port: 1112
eureka:
  registry:
    hostname: localhost
    port: 1111
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://${eureka.registry.hostname}:${eureka.registry.port}/eureka/
  instance:
    hostname: localhost

